name: Node.js CI
on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main','b1']
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Install npm packages
        run: |
          npm install
          npx playwright install
          nohup npm run dev > output.log 2>&1 &
          sleep 5
          curl -I http://localhost:1342/

      - name: Run playwright tests
        run: |
          npm run test:playwright


